### ISSUE TITLE
PSA: Only BufferGeometries are supported

### ISSUE THREAD

**Issue by markaren** [markaren/three.kt#11]
`<\*>Geometry` in `three.kt` are actually typeAliases for the `<\*>BufferGeometry` equivalent. 

I'm not planning to add the `Geometry` class. But give me a good reason why it should be included, and I might reconsider.

**Comment by EliasHasle** [comment]
Hei! 😄

I agree with you. `Geometry` is a candidate for deprecation in the mother project. It is remnants of an old and heavy API, and its use is no longer encouraged. They are already discussing whether it should even be rendered, or just be kept as a tool for constructing BufferGeometries iteratively. Of course, it could serve as that in your version too.

**Comment by Displee** [comment]
Threejs WebGL 2.0 renderer (since R95) only makes use of `BufferGeometry`. `Geometry` is a legacy format. It's impossible to render a `Geometry` in WebGL without converting it to a `BufferGeometry` first. I don't know whether this overhead is less performant in the JVM, but in browsers it's recommended (and faster) to use `BufferGeometry` because of less overhead.

You can drop `Geometry` imo.

**Comment by markaren** [comment]
Yeah, there is no plan to support `Geometry` and as people should be quite familiar with `BufferGeometry` by this point, there is no reason to have this "issue" up. Closing.
